Adapting semantic performance_calculator
argaman-aloni/sam_learning pull request #20
Opened 2024-07-18 13:44 UTC by oriKay

When encountered with a joint action, semantic calculator calculates the performance of each action inside the joint list.

2024-07-21 10:35 UTC, argaman-aloni requested changes
Create a new module that extends the original performance evaluation and use apply the appropriate logic for the multi-agent evaluation there, 

Notice that some parts of the evaluation might not be appropriate with the changes made to the code I'm my recent edits, for this reason it is preferable to add a new evaluation module and use it for the experiments.

2024-07-24 12:07 UTC, oriKay commented
This version of Ma_sam learns precision and recalls only for preconditions. No effects calculations supported yet.
The calculation is looking at each action in a joint_action, as single agent action, independently.

We discussed the problem of not extracting all relevant actions when dealing with random trajectories. 
This commit does not address this limitation.

2024-08-01 15:17 UTC, argaman-aloni commented on statistics/ma_performance_calculator.py
> +                    f"Calculating the preconditions' ma semantic performance for the action the state - {component.previous_state.serialize()}"
no need for "ma semantic" say "Calculating.... semantic performance for the agents' actions"

2024-08-01 15:17 UTC, argaman-aloni commented on statistics/ma_performance_calculator.py
> +class MaSamPerformanceCalculator(SemanticPerformanceCalculator):
Should be MA instead of Ma since these are two words :)

2024-08-01 15:17 UTC, argaman-aloni commented on statistics/ma_performance_calculator.py
> +    def export_semantic_performance(self, fold_num: int, iteration_num: int = 0) -> None:
you can just use the parent method, set some value to the effects (something like TBD or something), that way you don't have to re-implement the same method.

2024-08-01 15:17 UTC, argaman-aloni commented on statistics/ma_performance_calculator.py
> +    def export_combined_semantic_performance(self) -> None:
Same here.

2024-08-05 12:23 UTC, oriKay commented
Inserted SEMANTIC_PRECISION_STATS into the Semantic Calculator as a variable rather than global value in the same file.
Made sure no other file uses this variable. Also made sure it does not affect numeric sam's version of Semnatic Calc which inherits this class.
As numeric overrides the functions that use SEMANTIC_PRECISION_STATS, it's ok.

2024-09-11 06:08 UTC, closed without merging

2024-09-11 06:08 UTC, oriKay commented
A newer version of this issue exists